FROM prom/prometheus:v2.21.0

LABEL app="QIoT project - Prometheus"
LABEL maintainer="Rémi Verchère <remi.verchere@axians.com>"
LABEL major_version="1"
LABEL minor_version="0"

COPY prometheus.yml /etc/prometheus/
